language: objective-c
osx_image: xcode9
xcode_project: Project/EnumListProject.xcodeworkspace
xcode_scheme: EnumListProject



env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - gem install cocoapods
  - gem install fastlane
  - gem install xcov
  - gem install coveralls

script:
  - cd Project
  - fastlane test
